### ISSUE TITLE
No access to google drive file in avbert

### ISSUE THREAD

**Issue by Achi-kyw** [roger-tseng/av-superb#2]
```
Traceback (most recent call last):
  File "/home/achi/miniconda3/envs/av/lib/python3.9/site-packages/gdown/download.py", line 267, in download
    url = get_url_from_gdrive_confirmation(res.text)
  File "/home/achi/miniconda3/envs/av/lib/python3.9/site-packages/gdown/download.py", line 55, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses. Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/md0/user_achi/av-superb/run_downstream.py", line 309, in <module>
    main()
  File "/mnt/md0/user_achi/av-superb/run_downstream.py", line 304, in main
    runner = Runner(args, config)
  File "/mnt/md0/user_achi/av-superb/runner.py", line 61, in __init__
    self.upstream = self._get_upstream()
  File "/mnt/md0/user_achi/av-superb/runner.py", line 102, in _get_upstream
    model = Upstream(
  File "/mnt/md0/user_achi/av-superb/upstream_models/avbert/hubconf.py", line 48, in avbert
    return avbert_time(refresh=refresh, *args, **kwargs)
  File "/mnt/md0/user_achi/av-superb/upstream_models/avbert/hubconf.py", line 33, in avbert_time
    return avbert_url(refresh=refresh, *args, **kwargs)
  File "/mnt/md0/user_achi/av-superb/upstream_models/avbert/hubconf.py", line 24, in avbert_url
    return avbert_local(_urls_to_filepaths(ckpt, refresh=refresh, agent="gdown"), *args, **kwargs)
  File "/mnt/md0/user_achi/av-superb/utils/download.py", line 55, in _urls_to_filepaths
    paths = [url_to_path(url, refresh) for url in args]
  File "/mnt/md0/user_achi/av-superb/utils/download.py", line 55, in <listcomp>
    paths = [url_to_path(url, refresh) for url in args]
  File "/mnt/md0/user_achi/av-superb/utils/download.py", line 51, in url_to_path
    return _download(url_to_filename(url), url, refresh, agent=agent)
  File "/mnt/md0/user_achi/av-superb/utils/download.py", line 21, in _download
    gdown.download(url, filepath, use_cookies=False)
  File "/home/achi/miniconda3/envs/av/lib/python3.9/site-packages/gdown/download.py", line 278, in download
    raise FileURLRetrievalError(message)
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses.
        Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

        https://drive.google.com/u/0/uc?id=1T55DuJq0OYSdXVnDlOrgPSTwffVKsiFY&export=download&confirm=t&uuid=b73dc818-c9b0-49e8-a488-13b829fdbb7e&at=ANzk5s4TfW9_erYs4M9PH7KYuKzy:1681055195563

but Gdown can't. Please check connections and permissions.
```

It seems that avbert link to an google drive file, but I am not able to access.

**Comment by roger-tseng** [comment]
Hello,

The original link by the AVBERT authors seems to have expired. 
Here is a command that downloads the checkpoint from an alternative source to the expected local filepath:
`wget https://huggingface.co/rogertseng/avsuperb_upstreams/resolve/main/avbert.pth?download=true -O ~/.cache/torch/hub/s3prl_cache/e7e8661c9494e91d73b971938fa8c73ade6be2e4eabdd32c2a3208decc6bd42d`
